# Default values for ocp-auto-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#

namespace: ocp-etcd-backup
displayname: "Backup ETCD Automation"
description: "Openshift Backup Automation Tool"

pvc:
  name: etcd-backup-pvc
  # using one accessMode, which is usually sufficient
  accessMode: "ReadWriteOnce"
  size: "100Gi"
  storageClass: "gp2" 

# Reuse of default _helper methods would be a better option maybe
serviceAccount: openshift-backup

cronjob:
  name: cronjob-etcd-backup
  schedule: "*/5 * * * *"

clusterrolename: cluster-etcd-backup
clusterrolebinding: openshift-backup
clusterrolebindingPrivileged: etcd-backup-scc-privileged

